services:
  tests:
    build:
      context: .
      target: tests

    pull_policy: build

    image: assembly-assistant-x5-tests:0.1.1

    environment:
      DB_USER: postgres
      DB_PASSWORD: localbase
      DB_HOST: test_postgres
      DB_PORT: 5432
      DB_NAME: assembly_assistant_x5_test

    depends_on:
      test_postgres:
        condition: service_healthy

  test_postgres:

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      retries: 5
      interval: 3s
      timeout: 5s
      start_period: 5s

    image: postgres:18

    environment:
      POSTGRES_PASSWORD: localbase
