"""initial schema

Revision ID: bdc939471088
Revises: 
Create Date: 2026-08-25 12:43:35.105256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc939471088'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.CheckConstraint(
        "name <> ''",
        name="clients_name_not_empty"
    ),
    sa.CheckConstraint(
        "phone <> ''",
        name="clients_phone_not_empty"
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.Text(), nullable=False),
    sa.Column('house', sa.Text(), nullable=False),
    sa.Column('floor', sa.Text(), nullable=True),
    sa.Column('entrance', sa.Text(), nullable=True),
    sa.Column('apartment', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.CheckConstraint(
        "street <> ''",
        name="addresses_street_not_empty"
    ),
    sa.CheckConstraint(
        "house <> ''",
        name="addresses_house_not_empty"
    ),
    sa.CheckConstraint(
        "floor <> ''",
        name="addresses_floor_not_empty"
    ),
    sa.CheckConstraint(
        "entrance <> ''",
        name="addresses_entrance_not_empty"
    ),
    sa.CheckConstraint(
        "apartment <> ''",
        name="addresses_apartment_not_empty"
    ),
    sa.CheckConstraint(
        "comment <> ''",
        name="addresses_comment_not_empty"
    ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('addresses_client_id_idx', 'addresses', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('addresses_client_id_idx', table_name='addresses')
    op.drop_table('addresses')
    op.drop_table('clients')
    # ### end Alembic commands ###
